# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BSides Cairo"
email: "bsidescairo@gmail.com"
description: "BSides Cairo is an information security conference!"
baseurl: "/"
url: "bsides-cairo.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "BSides Cairo"
organizerAlternateName: "BSides Cairo"
organizerDescription: "BSides Cairo is an information security conference!"
organizerEmail: "bsidescairo@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://twitter.com/bsidescairo"

# Head
metaKeywords: "event, cybersecurity, bsides, cairo, programming, hacking, malwares, blue team, red team"
twitterAccount: "@BSidesCairo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfJ6eyQrZJvRxXRdpYjTdckf9hY-wKVzLwEoAswxNbI1pCUFg/viewform"
c4sponsorsUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdWS-J6viFUrOrEmiblQ7t275pgyLvv6QDY6B9ev4plcLUF6A/viewform"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "News"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 #- {permalink: "/logistics/", text: "workshops"}
 #- {permalink: "/hackathon/", text: "CTF"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfJ6eyQrZJvRxXRdpYjTdckf9hY-wKVzLwEoAswxNbI1pCUFg/viewform", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfJ6eyQrZJvRxXRdpYjTdckf9hY-wKVzLwEoAswxNbI1pCUFg/viewform", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "24-25th of June, 2022 (Localhost Edition)"
typeoutTextValues: '"", "BSides Cairo 2022","Awakening The Hacker Pharaoh!"'
typeoutFallback: "BSides Cairo 2022"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfJ6eyQrZJvRxXRdpYjTdckf9hY-wKVzLwEoAswxNbI1pCUFg/viewform", text: "Become a speaker"}
 - {permalink: "/#subscribe", text: "Get Access"}

# About Block
aboutTitle: "About BSides Cairo"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest BSides event in the country carefully crafted for you by the professional InfoSec community! Awesome pure technical talks and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite topics with talented security professionals!" }
 - {title: "CTF", image: "hackathon.jpg", text: "Full-day realistic security challenges! Want some real team hacking on friday? Grab your team and join our CTF!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure technical cyber security technologies"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "2", specialCharacter: "", info: "previous editions", detail: "BSides Cairo story began back in 2019"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 10
rockstarSpeakersTitle: "2022 New Speakers"
rockstarSpeakersButtonText: "Show all speakers!"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "The GrEEK Campus"
eventLocationLink: "https://thegreekcampus.com/"
eventStreetAddress: "171 El Tahrir, Downtown, Abdeen"
eventAddressLocality: "Cairo"
eventAddressLocalityRegion: "Cairo"
eventPostalCode: "79000"
eventAddressCountry: "Egypt"
eventStartTime: "2021-06-24T10:00"
eventDoorTime: "09:00"
eventEndTime: "2021-10-25T20:00"
eventPlaceCoordinates: "30.044658381882243, 31.238914227203516"
mapCenterCoordinates: "30.044658381882243, 31.238914227203516"
mapMobileCenterCoordinates: "30.044658381882243, 31.238914227203516"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "The GrEEK Campus"
venueFeatures: ["Huge conference hall with full of services campus.","Seperate rooms for side discussions and workshops.", "Cairo’s first technology and innovation park in the heart of Egypt.","Unfortunately, this year's event will be virtual."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "BSidesCAI"
twitterFeed: "https://twitter.com/search?q=%23BSidesCAI"

# Partners Block
organizersTitle: "Sponsors"
#partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Once Again, Together We Write History!"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

subscribeInfo: "This year's event is totally FREE. Registration will open soon. Number of seats are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets Registration"
ticketsInfo: "Tickets grant access to all conference sections."
#Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price.
ticketsOffers:
 -
  name: "Academic"
  price: "0.0"
  priceCurrency: "USD"
  ticketsNumber: "150"
  ribbon: "-100%"
  #buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Intended for our academic fellows.", "Full acess for the two days."]
  validFrom: "2022-06-18T10:00"
  validThrough: "2022-06-25T14:00"
 -
  name: "Professionals"
  price: "0.0"
  priceCurrency: "USD"
  ticketsNumber: "100"
  ribbon: "-100%"
  #buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Intended for our industry professionals.", "Full acess for the two days."]
  validFrom: "2022-06-18T10:00"
  validThrough: "2022-06-25T14:00"
 -
  name: "Student"
  price: "0.0"
  priceCurrency: "USD"
  ticketsNumber: "50"
  ribbon: "-100%"
  #buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Intended for our undergrad students.", "Full acess for the two days."]
  validFrom: "2022-06-18T10:00"
  validThrough: "2022-06-25T14:00"

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/bsidescairo", icon: "twitter"}
 - {link: "https://www.facebook.com/BSCairo/", icon: "facebook"}
 - {link: "https://www.youtube.com/channel/UCA70YUdXBf_2PN36qkec9Zg", icon: "youtube"}
 - {link: "https://www.linkedin.com/company/bsides-cairo/", icon: "linkedin"}
footerBlocks:
 #-
  #title: "Links"
  #links:
   #- {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   #- {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bsidescairo@gmail.com", text: "BSides Cairo"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "BSides Cairo"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Bsides Cairo is an information security conference which will host information security professionals, security researchers, academics, undergrads, graduate students, corporations and any person who wants to share knowledge and learn from others.
We look forward to bring together experts, researchers and students to share their thoughts, projects, experiences to face together the current information security challenges of our days and to come up with new ideas and collaborations.

Our mission is to create a more knowledge-based event regardless of age, academic title or industrial position, and to provide the egyptian community with an alternative event by removing the current common industrial and marketing-driven conferences barriers and providing a more technical approach regarding all the organization aspects of an information security conference, from the speakers, to the target audience."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "30.044658381882243, 31.238914227203516"
logisticsMapMobileCenterCoordinates: "30.044658381882243, 31.238914227203516"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Cairo"
#directionDetailsCards:
# - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
# - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "30.044658381882243, 31.238914227203516"
hackathonMapCenterCoordinates: "30.044658381882243, 31.238914227203516"
hackathonMapMobileCenterCoordinates: "30.044658381882243, 31.238914227203516"
